### PR TITLE
At2 165 configure subarray

### PR DESCRIPTION
**Pull request by snehalpersistent**
Request your review on the code added in CDM library for  configure subarray. It has only one unit test for schema (configure request). Response tests are not added as we are not dealing with a responseschema as of now. More unit tests to be added

### CODE REVIEW

**Review by mark-nicol — APPROVED** [review]
Nice work. This looks an excellent start Snehal. Happy to merge this. To count as done it will need some work on the test. Perhaps a very basic check that if two subarray configurations have the same parameters that they are equal but I'd want to check with Stewart if that makes sense.

I wondered whether adding a Target class would simplify things for any users by hiding the use of the astropy classes. I'll check in a basic version to this branch after merging your changes first so you can see what you think.

**Comment by bravostuzero** [comment]
We need to get unit tests committed for this code ASAP. In future, we can _not_ merge code to master for cdm-shared-library without full test coverage. Don't worry about committing early to hit story deadlines - if adding comprehensive tests takes an extra sprint, I'lll back you up 100% with that, no matter how long it takes. We're aiming for 100% test coverage for the CDM, even for the most trivial-looking code. The reason is that Python is a dynamic language, and with no compilation errors you never know for sure whether code works until it has run, even for tiny little things like __str__ representations. We have to be strict with the CDM as is will be used by several other teams, and if the code breaks then it's likely that the whole system prototype will fail.

**Comment by bravostuzero** [comment]
@snehalpersistent, if you'd like a session on adding tests to the CDM, I'm sure we can schedule that for the F2F this week.

**Comment by snehalpersistent** [comment]
Yes, I agree it needs more unit tests.  However, to make this version usable from OET,I think it needs patch release, versioning etc from main branch.  I'm unable to use the new CDM code from OET until it happens .There might be another way to do this ? We will continue adding unit tests to get full test coverage and yes, I session on pytest will be useful.Thanks :)

**Pull request merged**
